export const ENDPOINTS = {
    CLIENTS: "/clients",
    EMPLOYEES: "/employees",
    JOBS: "/jobs",
    SUBJOBS: "/sub-jobs",
    COMMANDS: "/commands",
    PRODUCTS: "/products",
    COMMAND_PRODUCTS: "/command-products",
    DASHBOARD_GENERAL_STATS: "/dashboard/general-stats",
    REPORTS: "/reports",
    TASKS: "/tasks",

    CLIENT_BY_ID: "/clients/:id",
    EMPLOYEE_BY_ID: "/employees/:id",
    JOB_BY_ID: "/jobs/:id",
    SUBJOB_BY_ID: "/sub-jobs/:id",
    JOBS_BY_CLIENT: "/jobs?fkClient=:clientId",
    COMMAND_BY_ID: "/commands/:id",
    PRODUCT_BY_ID: "/products/:id",
    DASHBOARD_BAR_STATS: "/dashboard/bar-stats/:idClient",
    COMMANDS_OPEN: "/commands?status=:status",
    COMMANDS_CLOSED: "/commands?status=:status",
    COMMAND_PRODUCTS_BY_COMMAND: "/command-products?fkComanda=:commandId",

    getClientById: (id) => `/clients/${id}`,
    getEmployeeById: (id) => `/employees/${id}`,
    getJobById: (id) => `/jobs/${id}`,
    getSubJobById: (id) => `/sub-jobs/${id}`,
    getJobsByClient: (clientId) => `/jobs?fkClient=${clientId}`,
    getCommandById: (id) => `/commands/${id}`,
    getProductById: (id) => `/products/${id}`,
    getDashboardBarStats: (idClient) => `/dashboard/bar-stats/${idClient}`,
    getCommandProductsByCommand: (commandId) => `/command-products?fkComanda=${commandId}`,
    getCommandProductsByCommand: (productId) => `/command-products?${productId}`
};